name: Build and Publish Image

on:
  push:
    branches:
      - main

env:
  GCP_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: 'Google Cloud Authenticate'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'gcloud cli'
        uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true

      - name: 'configure Docker'
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: 'Build and Publish'
        run: |
          gcloud config set run/region us-central1
          docker build -t b4bcompute .
          docker tag b4bcompute us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/b4b-compute/b4bcompute
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/b4b-compute/b4bcompute
        env:
          GCP_CREDENTIALS: $GCP_CREDENTIALS

